# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dc_metadata.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x63_metadata.proto\x12\x0b\x64\x63_metadata\"\xb8\x01\n\x13\x44\x61taCapsuleMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nwriter_key\x18\x02 \x01(\x0c\x12\x18\n\x0b\x63reator_key\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x12\x19\n\x11\x64\x65\x63ryption_source\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63reation_timestamp\x18\x05 \x01(\x03\x12\x13\n\x06policy\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_creator_keyB\t\n\x07_policyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dc_metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATACAPSULEMETADATA']._serialized_start=35
  _globals['_DATACAPSULEMETADATA']._serialized_end=219
# @@protoc_insertion_point(module_scope)
