# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dc_record.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x63_record.proto\x12\tdc_record\"\x95\x02\n\x11\x44\x61taCapsuleRecord\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\x03\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x13\n\x0bparent_hash\x18\x04 \x01(\x0c\x12\x0c\n\x04hash\x18\x05 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x10\n\x08msg_type\x18\x07 \x01(\t\x12\x1d\n\x15len_plaintext_payload\x18\x08 \x01(\x03\x12\x17\n\nreply_addr\x18\t \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0cpayload_hmac\x18\n \x01(\tH\x01\x88\x01\x01\x12\x11\n\x08verified\x18\xa1\x1f \x01(\x08\x42\r\n\x0b_reply_addrB\x0f\n\r_payload_hmacb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dc_record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATACAPSULERECORD']._serialized_start=31
  _globals['_DATACAPSULERECORD']._serialized_end=308
# @@protoc_insertion_point(module_scope)
