# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/create.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sign_pb2 as sign__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15requests/create.proto\x1a\nsign.proto\"}\n\rCreateRequest\x12\x17\n\x0f\x63reater_pub_key\x18\x01 \x01(\x0c\x12\x16\n\x0ewriter_pub_key\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12&\n\x11\x63reater_signature\x18\x04 \x01(\x0b\x32\x0b.SignedHash\"7\n\x0e\x43reateResponse\x12%\n\x10server_signature\x18\x01 \x01(\x0b\x32\x0b.SignedHashb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.create_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEREQUEST']._serialized_start=37
  _globals['_CREATEREQUEST']._serialized_end=162
  _globals['_CREATERESPONSE']._serialized_start=164
  _globals['_CREATERESPONSE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
