# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/init.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13requests/init.proto\"\x9a\x01\n\x0bInitRequest\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.InitRequest.Type\x12\x1d\n\x10\x64\x61tacapsule_hash\x18\x02 \x01(\x0cH\x00\x88\x01\x01\"6\n\x04Type\x12\n\n\x06\x63reate\x10\x00\x12\t\n\x05write\x10\x01\x12\x08\n\x04read\x10\x02\x12\r\n\tsubscribe\x10\x03\x42\x13\n\x11_datacapsule_hash\"$\n\x0cInitResponse\x12\x14\n\x0cinit_success\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.init_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITREQUEST']._serialized_start=24
  _globals['_INITREQUEST']._serialized_end=178
  _globals['_INITREQUEST_TYPE']._serialized_start=103
  _globals['_INITREQUEST_TYPE']._serialized_end=157
  _globals['_INITRESPONSE']._serialized_start=180
  _globals['_INITRESPONSE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
