# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/read.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sign_pb2 as sign__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13requests/read.proto\x1a\nsign.proto\"Y\n\x0bReadRequest\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.ReadRequest.Type\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\"\x1b\n\x04Type\x12\x08\n\x04\x64\x61ta\x10\x00\x12\t\n\x05proof\x10\x01\"\x1c\n\x0c\x44\x61taResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"H\n\rProofResponse\x12\x1e\n\x04root\x18\x01 \x01(\x0b\x32\x0b.SignedHashH\x00\x88\x01\x01\x12\x0e\n\x06hashes\x18\x02 \x03(\x0c\x42\x07\n\x05_rootb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.read_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=35
  _globals['_READREQUEST']._serialized_end=124
  _globals['_READREQUEST_TYPE']._serialized_start=97
  _globals['_READREQUEST_TYPE']._serialized_end=124
  _globals['_DATARESPONSE']._serialized_start=126
  _globals['_DATARESPONSE']._serialized_end=154
  _globals['_PROOFRESPONSE']._serialized_start=156
  _globals['_PROOFRESPONSE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
