# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/subscribe.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18requests/subscribe.proto\"\x9e\x01\n\x10SubscribeRequest\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.SubscribeRequest.Type\x12\x10\n\x03num\x18\x02 \x01(\x06H\x00\x88\x01\x01\"J\n\x04Type\x12\x0c\n\x08last_num\x10\x00\x12\x11\n\rname_from_num\x10\x01\x12\x11\n\rnum_from_name\x10\x02\x12\x0e\n\nwait_after\x10\x03\x42\x06\n\x04_num\"I\n\x11SubscribeResponse\x12\x10\n\x03num\x18\x01 \x01(\x06H\x00\x88\x01\x01\x12\x11\n\x04hash\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\x06\n\x04_numB\x07\n\x05_hashb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.subscribe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=29
  _globals['_SUBSCRIBEREQUEST']._serialized_end=187
  _globals['_SUBSCRIBEREQUEST_TYPE']._serialized_start=105
  _globals['_SUBSCRIBEREQUEST_TYPE']._serialized_end=179
  _globals['_SUBSCRIBERESPONSE']._serialized_start=189
  _globals['_SUBSCRIBERESPONSE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
