# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests/write.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sign_pb2 as sign__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14requests/write.proto\x1a\nsign.proto\"\x86\x02\n\x0cWriteRequest\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.WriteRequest.Type\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x1c\n\x0fsequence_number\x18\x03 \x01(\x06H\x01\x88\x01\x01\x12%\n\x0b\x63ommit_root\x18\x04 \x01(\x0b\x32\x0b.SignedHashH\x02\x88\x01\x01\x12\x1c\n\x0f\x61\x64\x64itional_hash\x18\x05 \x01(\x0cH\x03\x88\x01\x01\"\x1d\n\x04Type\x12\t\n\x05write\x10\x00\x12\n\n\x06\x63ommit\x10\x01\x42\x07\n\x05_dataB\x12\n\x10_sequence_numberB\x0e\n\x0c_commit_rootB\x12\n\x10_additional_hash\"P\n\rWriteResponse\x12*\n\x10server_signature\x18\x01 \x01(\x0b\x32\x0b.SignedHashH\x00\x88\x01\x01\x42\x13\n\x11_server_signatureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests.write_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WRITEREQUEST']._serialized_start=37
  _globals['_WRITEREQUEST']._serialized_end=299
  _globals['_WRITEREQUEST_TYPE']._serialized_start=205
  _globals['_WRITEREQUEST_TYPE']._serialized_end=234
  _globals['_WRITERESPONSE']._serialized_start=301
  _globals['_WRITERESPONSE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
